name: Code Coverage

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    with:
      python_version: '3.11'
      coverage_source: 'hivemind_cli_terminal'
      test_path: 'tests/'
      test_extras: 'e2e'
      min_coverage: 0
